# -*- coding: utf-8 -*-
# See LICENSE file for full copyright and licensing details.
"""Importing models."""
from . import magento_instance
from . import common_log_book_ept
from . import common_log_lines_ept
from . import magento_customer_data_queue_ept
from . import magento_customer_data_queue_line_ept
from . import magento_storeview
from . import magento_website
from . import delivery_carrier
from . import magento_delivery_carrier
from . import ir_cron
from . import magento_payment_method
from . import magento_product_product
from . import product_product
from . import product_template
from . import magento_product_template
from . import magento_product_image
from . import sync_import_magento_product_queue
from . import sync_import_magento_product_queue_line
from . import common_product_image_ept
from . import magento_order_data_queue_ept
from . import magento_order_data_queue_line_ept
from . import res_partner
from . import magento_inventory_locations
from . import stock_picking
from . import account_move
from . import sale_order
from . import sale_order_line
from . import stock_move
from . import import_magento_order_status
from . import sale_workflow_process_ept
from . import data_queue_mixin_ept
from . import account
from . import magento_financial_status_ept
from . import res_company
from . import magento_res_partner_ept
from . import magento_api_request_page
from . import magento_attribute_set
from . import magento_product_attribute
from . import magento_attribute_option
from . import magento_attribute_group
from . import product_attribute
from . import magento_product_category
from . import magento_tax_class
