# -*- coding: utf-8 -*-

from . import magento_instance
from . import magento_storeview
from . import magento_website
from . import delivery_carrier
from . import magento_delivery_carrier
from . import ir_cron
from . import magento_payment_method
from . import magento_product_product
from . import product_product
from . import res_partner
from . import magento_inventory_locations
from . import stock_picking
from . import account_move
from . import sale_order
from . import sale_order_line
from . import stock_move
from . import import_magento_order_status
from . import account
from . import magento_financial_status
from . import magento_res_partner
from . import magento_product_category
from . import magento_product_log_book
from . import magento_orders_log_book
from . import magento_configurable_product
from . import product_attribute
from . import product_product
from . import product_public_category
from . import config_product_attribute
from . import account_fiscal_position
from . import sale_workflow_process
from . import vendor_stock
from . import product_pricelist
