# -*- coding: utf-8 -*-

from . import magento_instance
from . import magento_storeview
from . import magento_website
from . import magento_delivery_carrier
from . import ir_cron
from . import magento_payment_method
from . import magento_product_product
from . import product_product
from . import sale_order
from . import sale_order_line
from . import res_partner
from . import stock
from . import account
from . import magento_financial_status
from . import magento_res_partner
from . import magento_product_category
from . import magento_log_books
from . import magento_configurable_product
from . import product_attribute
from . import product_product
from . import product_public_category
from . import product_page_attribute
from . import sale_workflow_process
from . import product_pricelist
from . import magento_async_bulk_logs
from . import product_template
from . import product_image
from . import magento_special_pricing